---

- name: install nut
  apt:
    name: nut
    state: present
  become: yes

- name: nut configs
  template:
    src: "{{ item }}.j2"
    dest: "/etc/nut/{{ item }}"
    mode: 0640
    owner: root
    group: nut
  with_items:
    - ups.conf
    - nut.conf
  become: yes
  notify:
    - restart_nut_driver
    - restart_nut_server
